INSERT INTO location_dimension (location_key, location_state) VALUES ('1','Alabama');
INSERT INTO location_dimension (location_key,location_state) VALUES ('2','Alaska');
INSERT INTO location_dimension (location_key, location_state) VALUES ('3','Arizona');
INSERT INTO location_dimension (location_key, location_state) VALUES ('4','Arkansas');
INSERT INTO location_dimension (location_key, location_state) VALUES ('5','California');
INSERT INTO location_dimension (location_key, location_state) VALUES ('6','Colorado');
INSERT INTO location_dimension (location_key, location_state) VALUES ('7','Connecticut');
INSERT INTO location_dimension (location_key, location_state) VALUES ('8','Delaware');
INSERT INTO location_dimension (location_key, location_state) VALUES ('9','District of Columbia');
INSERT INTO location_dimension (location_key, location_state) VALUES ('10','Florida');
INSERT INTO location_dimension (location_key, location_state) VALUES ('11','Georgia');
INSERT INTO location_dimension (location_key, location_state) VALUES ('12','Hawaii');
INSERT INTO location_dimension (location_key, location_state) VALUES ('13','Idaho');
INSERT INTO location_dimension (location_key, location_state) VALUES ('14','Illinois');
INSERT INTO location_dimension (location_key, location_state) VALUES ('15','Indiana');
INSERT INTO location_dimension (location_key, location_state) VALUES ('16','Iowa');
INSERT INTO location_dimension (location_key, location_state) VALUES ('17','Kansas');
INSERT INTO location_dimension (location_key, location_state) VALUES ('18','Kentucky');
INSERT INTO location_dimension (location_key, location_state) VALUES ('19','Louisiana');
INSERT INTO location_dimension (location_key, location_state) VALUES ('20','Maine');
INSERT INTO location_dimension (location_key, location_state) VALUES ('21','Maryland');
INSERT INTO location_dimension (location_key, location_state) VALUES ('22','Massachusetts');
INSERT INTO location_dimension (location_key,location_state) VALUES ('23','Michigan');
INSERT INTO location_dimension (location_key, location_state) VALUES ('24','Minnesota');
INSERT INTO location_dimension (location_key, location_state) VALUES ('25','Mississippi');
INSERT INTO location_dimension (location_key, location_state) VALUES ('26','Missouri');
INSERT INTO location_dimension (location_key, location_state) VALUES ('27','Montana');
INSERT INTO location_dimension (location_key, location_state) VALUES ('28','Nebraska');
INSERT INTO location_dimension (location_key, location_state) VALUES ('29','Nevada');
INSERT INTO location_dimension (location_key, location_state) VALUES ('30','New Hampshire');
INSERT INTO location_dimension (location_key, location_state) VALUES ('31','New Jersey');
INSERT INTO location_dimension (location_key, location_state) VALUES ('32','New Mexico');
INSERT INTO location_dimension (location_key, location_state) VALUES ('33','New York');
INSERT INTO location_dimension (location_key, location_state) VALUES ('34','North Carolina');
INSERT INTO location_dimension (location_key, location_state) VALUES ('35','Ohio');
INSERT INTO location_dimension (location_key, location_state) VALUES ('36','Oklahoma');
INSERT INTO location_dimension (location_key, location_state) VALUES ('37','Oregon');
INSERT INTO location_dimension (location_key, location_state) VALUES ('38','Pennsylvania');
INSERT INTO location_dimension (location_key, location_state) VALUES ('39','Rhode Island');
INSERT INTO location_dimension (location_key, location_state) VALUES ('40','South Carolina');
INSERT INTO location_dimension (location_key, location_state) VALUES ('41','South Dakota');
INSERT INTO location_dimension (location_key, location_state) VALUES ('42','Tennessee');
INSERT INTO location_dimension (location_key, location_state) VALUES ('43','Texas');
INSERT INTO location_dimension (location_key, location_state) VALUES ('44','Utah');
INSERT INTO location_dimension (location_key, location_state) VALUES ('45','Vermont');
INSERT INTO location_dimension (location_key, location_state) VALUES ('46','Virginia');
INSERT INTO location_dimension (location_key, location_state) VALUES ('47','Washington');
INSERT INTO location_dimension (location_key, location_state) VALUES ('48','West Virginia');
INSERT INTO location_dimension (location_key, location_state) VALUES ('49','Wisconsin');
INSERT INTO location_dimension (location_key, location_state) VALUES ('50','Wyoming');